default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: api_starter_development

  <<: *default
  database: api_starter_test

production:
  <<: *default
  database: api_starter_production
